import { NextResponse } from 'next/server';
import { Resend } from 'resend';

/**
 * GET /api/cron/daily-summary
 *
 * Runs at 11:00 UTC = 7:00 AM EDT (summer) / 6:00 AM EST (winter)
 * via Vercel cron (see vercel.json). Sends a digest email to
 * contact@ultrashinecleaningfl.com summarizing yesterday's leads.
 *
 * Vercel automatically passes an Authorization header on cron runs:
 *   "Bearer ${CRON_SECRET}" (auto-generated by Vercel)
 * We don't need to manually set CRON_SECRET — Vercel handles it.
 */

const TO_EMAIL = 'contact@ultrashinecleaningfl.com';
const FROM_EMAIL = 'Ultra Shine Daily <onboarding@resend.dev>';
const SITE_URL = 'https://ultrashinecleaningfl.com';

type LeadKind = 'quote' | 'application';
type Lead = {
  id: string;
  kind: LeadKind;
  name: string;
  city?: string;
  createdAt: Date;
  phone?: string;
  email?: string;
};

function parseLead(email: any): Lead | null {
  const subject: string = email.subject ?? '';
  const createdAt = email.created_at ? new Date(email.created_at) : new Date();

  let kind: LeadKind | null = null;
  let parts: string[] = [];

  if (/^New Quote/i.test(subject)) {
    kind = 'quote';
    parts = subject.replace(/^New Quote\s*·\s*/i, '').split(/\s*·\s*/);
  } else if (/^New Cleaner Application/i.test(subject)) {
    kind = 'application';
    parts = subject.replace(/^New Cleaner Application\s*·\s*/i, '').split(/\s*·\s*/);
  }
  if (!kind) return null;

  return {
    id: email.id,
    kind,
    name: parts[0] || 'Unknown',
    city: parts[1],
    createdAt,
  };
}

function buildHtml(yesterdayLeads: Lead[], weekToDateCount: number, dayLabel: string): string {
  const quoteCount = yesterdayLeads.filter((l) => l.kind === 'quote').length;
  const appCount = yesterdayLeads.filter((l) => l.kind === 'application').length;
  const total = yesterdayLeads.length;

  const leadsBlock = total === 0
    ? `<div style="background:#fff;border:1px dashed rgba(28, 97, 240,0.20);border-radius:10px;padding:24px;text-align:center;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;color:#1C61F0;opacity:0.8;font-size:15px;">No new leads yesterday. The site is up + working — just a quiet day. Use this time to nudge IG / Google reviews.</div>`
    : `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;border:1px solid rgba(28, 97, 240,0.12);">
        ${yesterdayLeads
          .map(
            (l) => `<tr>
              <td style="padding:14px 18px;border-bottom:1px solid rgba(28, 97, 240,0.08);">
                <div style="font-size:10px;letter-spacing:0.28em;text-transform:uppercase;color:#1C61F0;margin-bottom:4px;font-weight:600;">
                  ${l.kind === 'quote' ? '✦ Quote Request' : '✦ Cleaner Application'}
                </div>
                <div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-weight:400;font-size:17px;color:#002C98;">
                  ${l.name}${l.city ? `<span style="color:#1C61F0;opacity:0.6;font-size:14px;"> · ${l.city}</span>` : ''}
                </div>
                <div style="font-size:11px;color:#1C61F0;opacity:0.6;margin-top:4px;">
                  ${l.createdAt.toLocaleString('en-US', { timeZone: 'America/New_York', hour: 'numeric', minute: '2-digit', hour12: true })} ET
                </div>
              </td>
            </tr>`
          )
          .join('')}
      </table>`;

  return `<!doctype html>
<html>
<body style="margin:0;padding:0;background:#FFFFFF;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;color:#002C98;">
  <div style="max-width:640px;margin:0 auto;padding:36px 24px 60px;">

    <!-- HEADER -->
    <div style="margin-bottom:24px;">
      <div style="font-size:11px;letter-spacing:0.32em;text-transform:uppercase;color:#1C61F0;opacity:0.7;margin-bottom:6px;">Daily Summary · ${dayLabel}</div>
      <h1 style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-weight:300;font-size:36px;letter-spacing:-0.5px;margin:0;color:#002C98;line-height:1.05;">
        ${total === 0 ? '<em style="color:#1C61F0;">No new leads</em> yesterday.' :
          total === 1 ? '<em style="color:#1C61F0;">1</em> new lead yesterday.' :
          `<em style="color:#1C61F0;">${total}</em> new leads yesterday.`}
      </h1>
      ${total > 0 ? `<div style="font-size:14px;color:#1C61F0;opacity:0.8;margin-top:8px;">
        ${quoteCount > 0 ? `${quoteCount} quote${quoteCount > 1 ? 's' : ''}` : ''}${quoteCount > 0 && appCount > 0 ? ' · ' : ''}${appCount > 0 ? `${appCount} cleaner application${appCount > 1 ? 's' : ''}` : ''}
      </div>` : ''}
    </div>

    <!-- LEADS BLOCK -->
    ${leadsBlock}

    <!-- WEEK-TO-DATE -->
    <div style="margin-top:24px;padding:18px 20px;background:#002C98;color:#FFFFFF;border-radius:10px;text-align:center;">
      <div style="font-size:10px;letter-spacing:0.3em;text-transform:uppercase;opacity:0.7;margin-bottom:6px;">Week to date</div>
      <div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-weight:300;font-size:32px;letter-spacing:-0.5px;">
        <em style="color:#1C61F0;">${weekToDateCount}</em> lead${weekToDateCount === 1 ? '' : 's'} this week
      </div>
    </div>

    <!-- CTA -->
    <div style="text-align:center;margin-top:28px;">
      <a href="${SITE_URL}/admin" style="display:inline-block;background:#1C61F0;color:#002C98;padding:14px 32px;border-radius:999px;font-family:-apple-system,sans-serif;font-weight:500;font-size:13px;letter-spacing:0.2em;text-transform:uppercase;text-decoration:none;">
        Open Dashboard →
      </a>
    </div>

    <!-- FOOTER -->
    <div style="margin-top:32px;text-align:center;font-size:11px;color:#1C61F0;opacity:0.5;line-height:1.5;">
      Ultra Shine Cleaning · Daily Summary<br/>
      Sent every morning at 7am ET · Manage at <a href="${SITE_URL}/admin" style="color:#1C61F0;">${SITE_URL}/admin</a>
    </div>
  </div>
</body>
</html>`;
}

export async function GET(req: Request) {
  // Vercel passes Authorization header on cron runs
  const authHeader = req.headers.get('authorization');
  const cronSecret = process.env.CRON_SECRET;

  // Only enforce auth check in production where CRON_SECRET is set
  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ ok: false, error: 'RESEND_API_KEY not set' }, { status: 500 });
  }

  try {
    const resend = new Resend(apiKey);

    // Pull last 100 emails (covers yesterday + week-to-date for normal volume)
    const res: any = await resend.emails.list({ limit: 100 });
    const data: any[] = res?.data?.data ?? res?.data ?? [];

    const leads = data.map(parseLead).filter((l): l is Lead => l !== null);

    // Yesterday window: 00:00–23:59 ET previous calendar day
    const now = new Date();
    const yesterdayStart = new Date(now);
    yesterdayStart.setUTCHours(4, 0, 0, 0); // 00:00 EDT = 04:00 UTC
    yesterdayStart.setUTCDate(yesterdayStart.getUTCDate() - 1);
    const yesterdayEnd = new Date(yesterdayStart);
    yesterdayEnd.setUTCDate(yesterdayEnd.getUTCDate() + 1);

    const yesterdayLeads = leads
      .filter((l) => l.createdAt >= yesterdayStart && l.createdAt < yesterdayEnd)
      .sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime());

    // Week-to-date (last 7 days)
    const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const weekToDateCount = leads.filter((l) => l.createdAt >= weekStart).length;

    const dayLabel = yesterdayStart.toLocaleDateString('en-US', {
      timeZone: 'America/New_York',
      weekday: 'long',
      month: 'long',
      day: 'numeric',
    });

    const total = yesterdayLeads.length;
    const subject =
      total === 0
        ? `📊 Daily Summary · No new leads yesterday`
        : total === 1
        ? `📊 Daily Summary · 1 new lead yesterday`
        : `📊 Daily Summary · ${total} new leads yesterday`;

    const { data: sendData, error: sendError } = await resend.emails.send({
      from: FROM_EMAIL,
      to: TO_EMAIL,
      subject,
      html: buildHtml(yesterdayLeads, weekToDateCount, dayLabel),
    });

    if (sendError) {
      console.error('[daily-summary] Resend send error:', sendError);
      return NextResponse.json({ ok: false, error: sendError.message }, { status: 500 });
    }

    console.log('[daily-summary] sent', { id: sendData?.id, leadsYesterday: total, weekToDate: weekToDateCount });
    return NextResponse.json({
      ok: true,
      sent: true,
      yesterdayCount: total,
      weekToDateCount,
      id: sendData?.id,
    });
  } catch (err: any) {
    console.error('[daily-summary] handler error', err);
    return NextResponse.json({ ok: false, error: err?.message ?? 'unknown' }, { status: 500 });
  }
}
