import { NextResponse } from 'next/server';
import { Resend } from 'resend';
import { getJobberMetrics, isJobberConfigured } from '../../../_lib/jobberClient';

/**
 * GET /api/cron/daily-summary
 *
 * Runs at 11:00 UTC = 7:00 AM EDT (summer) / 6:00 AM EST (winter)
 * via Vercel cron (see vercel.json). Sends a digest email to
 * contact@ultrashinecleaningfl.com with:
 *   1. Yesterday's inbound leads (Resend)
 *   2. Today's scheduled jobs (Jobber, if connected)
 *   3. This week's revenue from paid invoices (Jobber)
 *   4. Outstanding / unpaid invoices total (Jobber)
 *   5. Week-to-date lead count
 *
 * Vercel automatically passes an Authorization header on cron runs:
 *   "Bearer ${CRON_SECRET}" (auto-generated by Vercel)
 * We don't need to manually set CRON_SECRET — Vercel handles it.
 *
 * Visual style matches the recolored admin palette (dark slate grey
 * accents, near-black text, neutral chip colors — not the brand blue).
 */

const TO_EMAIL = 'contact@ultrashinecleaningfl.com';
const FROM_EMAIL = 'Ultra Shine Daily <onboarding@resend.dev>';
const SITE_URL = 'https://ultrashinecleaningfl.com';

// ---- Color palette (matches the recolored admin dashboard) ----
const C = {
  bg: '#f9fafb',
  cardBg: '#ffffff',
  border: '#e5e7eb',
  text: '#111827',
  textDim: '#6b7280',
  textVeryDim: '#9ca3af',
  accent: '#374151', // dark grey accent
  accentDark: '#111827',
  positive: '#166534',
  alertBg: '#fffbeb',
  alertBorder: '#fde68a',
  alertText: '#92400e',
} as const;

type LeadKind = 'quote' | 'application';
type Lead = {
  id: string;
  kind: LeadKind;
  name: string;
  city?: string;
  createdAt: Date;
};

function parseLead(email: any): Lead | null {
  const subject: string = email.subject ?? '';
  const createdAt = email.created_at ? new Date(email.created_at) : new Date();

  let kind: LeadKind | null = null;
  let parts: string[] = [];

  if (/^New Quote/i.test(subject)) {
    kind = 'quote';
    parts = subject.replace(/^New Quote\s*·\s*/i, '').split(/\s*·\s*/);
  } else if (/^New Cleaner Application/i.test(subject)) {
    kind = 'application';
    parts = subject.replace(/^New Cleaner Application\s*·\s*/i, '').split(/\s*·\s*/);
  }
  if (!kind) return null;

  return {
    id: email.id,
    kind,
    name: parts[0] || 'Unknown',
    city: parts[1],
    createdAt,
  };
}

const fmtMoney = (n: number) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(n);

function buildHtml(
  yesterdayLeads: Lead[],
  weekToDateCount: number,
  dayLabel: string,
  jobber: Awaited<ReturnType<typeof getJobberMetrics>> | null,
): string {
  const quoteCount = yesterdayLeads.filter((l) => l.kind === 'quote').length;
  const appCount = yesterdayLeads.filter((l) => l.kind === 'application').length;
  const total = yesterdayLeads.length;

  // ----- Leads block -----
  const leadsBlock =
    total === 0
      ? `<div style="background:${C.cardBg};border:1px dashed ${C.border};border-radius:12px;padding:24px;text-align:center;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;color:${C.textDim};font-size:14px;">No new leads yesterday. Use the quiet morning to nudge an existing client for a Google review.</div>`
      : `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;background:${C.cardBg};border-radius:12px;overflow:hidden;border:1px solid ${C.border};">
        ${yesterdayLeads
          .map(
            (l) => `<tr>
              <td style="padding:14px 18px;border-bottom:1px solid ${C.border};">
                <div style="font-size:10px;letter-spacing:0.24em;text-transform:uppercase;color:${C.textDim};margin-bottom:4px;font-weight:700;">
                  ${l.kind === 'quote' ? '✦ Quote Request' : '✦ Cleaner Application'}
                </div>
                <div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-weight:700;font-size:16px;color:${C.text};">
                  ${l.name}${l.city ? `<span style="color:${C.textDim};font-weight:400;font-style:italic;font-size:13px;"> · ${l.city}</span>` : ''}
                </div>
                <div style="font-size:11px;color:${C.textVeryDim};margin-top:4px;">
                  ${l.createdAt.toLocaleString('en-US', { timeZone: 'America/New_York', hour: 'numeric', minute: '2-digit', hour12: true })} ET
                </div>
              </td>
            </tr>`,
          )
          .join('')}
      </table>`;

  // ----- Jobber today's jobs block -----
  let jobberSection = '';
  if (jobber && !jobber.errorDetail) {
    const todayList = jobber.upcomingJobs
      .filter((j) => {
        if (!j.startAt) return false;
        const d = new Date(j.startAt);
        const today = new Date();
        return d.toDateString() === today.toDateString();
      })
      .slice(0, 6);

    const todayBlock =
      todayList.length === 0
        ? `<div style="padding:16px 18px;background:${C.cardBg};border:1px dashed ${C.border};border-radius:10px;color:${C.textDim};font-size:13px;text-align:center;">No jobs on the Jobber calendar today.</div>`
        : `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;background:${C.cardBg};border-radius:10px;overflow:hidden;border:1px solid ${C.border};">
            ${todayList
              .map((j) => {
                const time = j.startAt
                  ? new Date(j.startAt).toLocaleTimeString('en-US', {
                      timeZone: 'America/New_York',
                      hour: 'numeric',
                      minute: '2-digit',
                      hour12: true,
                    })
                  : 'Time TBD';
                return `<tr>
                  <td style="padding:12px 16px;border-bottom:1px solid ${C.border};">
                    <div style="font-family:-apple-system,sans-serif;font-weight:700;font-size:14px;color:${C.text};">${j.clientName}</div>
                    <div style="font-size:12px;color:${C.textDim};margin-top:2px;">${j.title}${j.address ? ` · ${j.address}` : ''}</div>
                  </td>
                  <td style="padding:12px 16px;border-bottom:1px solid ${C.border};text-align:right;white-space:nowrap;">
                    <div style="font-family:-apple-system,sans-serif;font-weight:600;font-size:12px;color:${C.accent};">${time}</div>
                  </td>
                </tr>`;
              })
              .join('')}
          </table>`;

    // Money + counts row (revenue, awaiting payment, active clients)
    const moneyRow = `
      <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:separate;border-spacing:8px 0;margin-top:14px;">
        <tr>
          <td width="33%" style="background:${C.cardBg};border:1px solid ${C.border};border-radius:10px;padding:14px 16px;vertical-align:top;">
            <div style="font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:${C.textDim};font-weight:700;margin-bottom:4px;">Revenue · this week</div>
            <div style="font-family:-apple-system,sans-serif;font-weight:700;font-size:20px;color:${C.text};letter-spacing:-0.01em;">${fmtMoney(jobber.thisWeekRevenue)}</div>
          </td>
          <td width="33%" style="background:${jobber.pendingInvoiceCount > 0 ? C.alertBg : C.cardBg};border:1px solid ${jobber.pendingInvoiceCount > 0 ? C.alertBorder : C.border};border-radius:10px;padding:14px 16px;vertical-align:top;">
            <div style="font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:${jobber.pendingInvoiceCount > 0 ? C.alertText : C.textDim};font-weight:700;margin-bottom:4px;">Awaiting payment</div>
            <div style="font-family:-apple-system,sans-serif;font-weight:700;font-size:20px;color:${C.text};letter-spacing:-0.01em;">${fmtMoney(jobber.pendingInvoiceTotal)}</div>
            <div style="font-size:10px;color:${C.textDim};margin-top:2px;">${jobber.pendingInvoiceCount} invoice${jobber.pendingInvoiceCount === 1 ? '' : 's'}</div>
          </td>
          <td width="33%" style="background:${C.cardBg};border:1px solid ${C.border};border-radius:10px;padding:14px 16px;vertical-align:top;">
            <div style="font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:${C.textDim};font-weight:700;margin-bottom:4px;">Active clients</div>
            <div style="font-family:-apple-system,sans-serif;font-weight:700;font-size:20px;color:${C.text};letter-spacing:-0.01em;">${jobber.activeClientCount}</div>
          </td>
        </tr>
      </table>`;

    jobberSection = `
      <div style="margin-top:32px;">
        <div style="font-size:11px;letter-spacing:0.28em;text-transform:uppercase;color:${C.textDim};font-weight:700;margin-bottom:10px;">JOBBER · TODAY</div>
        ${todayBlock}
        ${moneyRow}
      </div>`;
  }

  return `<!doctype html>
<html>
<body style="margin:0;padding:0;background:${C.bg};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;color:${C.text};">
  <div style="max-width:640px;margin:0 auto;padding:36px 24px 60px;">

    <!-- HEADER -->
    <div style="margin-bottom:24px;">
      <div style="font-size:11px;letter-spacing:0.28em;text-transform:uppercase;color:${C.textDim};font-weight:700;margin-bottom:6px;">Daily Summary · ${dayLabel}</div>
      <h1 style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-weight:700;font-size:32px;letter-spacing:-0.02em;margin:0;color:${C.text};line-height:1.05;">
        ${
          total === 0
            ? `<em style="color:${C.textDim};font-style:italic;">No new leads</em> yesterday.`
            : total === 1
              ? `<em style="color:${C.accent};font-style:italic;">1</em> new lead yesterday.`
              : `<em style="color:${C.accent};font-style:italic;">${total}</em> new leads yesterday.`
        }
      </h1>
      ${
        total > 0
          ? `<div style="font-size:14px;color:${C.textDim};margin-top:8px;">
        ${quoteCount > 0 ? `${quoteCount} quote${quoteCount > 1 ? 's' : ''}` : ''}${quoteCount > 0 && appCount > 0 ? ' · ' : ''}${appCount > 0 ? `${appCount} cleaner application${appCount > 1 ? 's' : ''}` : ''}
      </div>`
          : ''
      }
    </div>

    <!-- LEADS BLOCK -->
    ${leadsBlock}

    <!-- JOBBER SECTION (only if connected + no errors) -->
    ${jobberSection}

    <!-- WEEK-TO-DATE -->
    <div style="margin-top:32px;padding:18px 20px;background:${C.accentDark};color:#ffffff;border-radius:10px;text-align:center;">
      <div style="font-size:10px;letter-spacing:0.28em;text-transform:uppercase;opacity:0.6;margin-bottom:6px;font-weight:700;">Week to date</div>
      <div style="font-family:-apple-system,sans-serif;font-weight:700;font-size:28px;letter-spacing:-0.02em;">
        ${weekToDateCount} lead${weekToDateCount === 1 ? '' : 's'} this week
      </div>
    </div>

    <!-- CTA -->
    <div style="text-align:center;margin-top:28px;">
      <a href="${SITE_URL}/admin" style="display:inline-block;background:${C.accentDark};color:#ffffff;padding:14px 32px;border-radius:999px;font-family:-apple-system,sans-serif;font-weight:700;font-size:12px;letter-spacing:0.16em;text-transform:uppercase;text-decoration:none;">
        Open Dashboard →
      </a>
    </div>

    <!-- FOOTER -->
    <div style="margin-top:36px;text-align:center;font-size:11px;color:${C.textVeryDim};line-height:1.55;">
      Ultra Shine Cleaning · Daily Summary<br/>
      Sent every morning at 7am ET · Manage at <a href="${SITE_URL}/admin" style="color:${C.accent};">${SITE_URL}/admin</a>
    </div>
  </div>
</body>
</html>`;
}

export async function GET(req: Request) {
  // Vercel passes Authorization header on cron runs
  const authHeader = req.headers.get('authorization');
  const cronSecret = process.env.CRON_SECRET;

  // Only enforce auth check in production where CRON_SECRET is set
  if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ ok: false, error: 'RESEND_API_KEY not set' }, { status: 500 });
  }

  try {
    const resend = new Resend(apiKey);

    // Run Resend + Jobber pulls in parallel — both can be slow, no
    // reason to wait sequentially.
    const [emailsRes, jobberMetrics] = await Promise.all([
      resend.emails.list({ limit: 100 }) as Promise<any>,
      isJobberConfigured() ? getJobberMetrics() : Promise.resolve(null),
    ]);

    const data: any[] = emailsRes?.data?.data ?? emailsRes?.data ?? [];
    const leads = data.map(parseLead).filter((l): l is Lead => l !== null);

    // Yesterday window: 00:00–23:59 ET previous calendar day
    const now = new Date();
    const yesterdayStart = new Date(now);
    yesterdayStart.setUTCHours(4, 0, 0, 0); // 00:00 EDT = 04:00 UTC
    yesterdayStart.setUTCDate(yesterdayStart.getUTCDate() - 1);
    const yesterdayEnd = new Date(yesterdayStart);
    yesterdayEnd.setUTCDate(yesterdayEnd.getUTCDate() + 1);

    const yesterdayLeads = leads
      .filter((l) => l.createdAt >= yesterdayStart && l.createdAt < yesterdayEnd)
      .sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime());

    // Week-to-date (last 7 days)
    const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    const weekToDateCount = leads.filter((l) => l.createdAt >= weekStart).length;

    const dayLabel = yesterdayStart.toLocaleDateString('en-US', {
      timeZone: 'America/New_York',
      weekday: 'long',
      month: 'long',
      day: 'numeric',
    });

    const total = yesterdayLeads.length;
    const todayJobsCount = jobberMetrics
      ? jobberMetrics.upcomingJobs.filter((j) => {
          if (!j.startAt) return false;
          return new Date(j.startAt).toDateString() === new Date().toDateString();
        }).length
      : 0;

    // Subject line summarizes the most important number
    const subject =
      total === 0 && todayJobsCount === 0
        ? `Daily Summary · Quiet day ahead`
        : total === 0
          ? `Daily Summary · ${todayJobsCount} job${todayJobsCount === 1 ? '' : 's'} today, no new leads`
          : total === 1
            ? `Daily Summary · 1 new lead yesterday${todayJobsCount > 0 ? `, ${todayJobsCount} jobs today` : ''}`
            : `Daily Summary · ${total} new leads yesterday${todayJobsCount > 0 ? `, ${todayJobsCount} jobs today` : ''}`;

    const { data: sendData, error: sendError } = await resend.emails.send({
      from: FROM_EMAIL,
      to: TO_EMAIL,
      subject,
      html: buildHtml(yesterdayLeads, weekToDateCount, dayLabel, jobberMetrics),
    });

    if (sendError) {
      console.error('[daily-summary] Resend send error:', sendError);
      return NextResponse.json({ ok: false, error: sendError.message }, { status: 500 });
    }

    console.log('[daily-summary] sent', {
      id: sendData?.id,
      leadsYesterday: total,
      weekToDate: weekToDateCount,
      jobsToday: todayJobsCount,
      jobberConfigured: !!jobberMetrics,
    });
    return NextResponse.json({
      ok: true,
      sent: true,
      yesterdayCount: total,
      weekToDateCount,
      jobsToday: todayJobsCount,
      thisWeekRevenue: jobberMetrics?.thisWeekRevenue ?? null,
      id: sendData?.id,
    });
  } catch (err: any) {
    console.error('[daily-summary] handler error', err);
    return NextResponse.json({ ok: false, error: err?.message ?? 'unknown' }, { status: 500 });
  }
}
